package me.wcy.crouter.compiler

import me.wcy.router.annotation.Router

/**
 * Created by wcy on 2019/7/19.
 */
object ProcessorUtils {
    const val PARAM_NAME = "routerSet"
    const val METHOD_NAME = "loadRouter"
    const val PACKAGE_NAME = "me.wcy.router.annotation.loader"
    const val JAVADOC = "DO NOT EDIT THIS FILE! IT WAS GENERATED BY CROUTER.\n"

    fun assembleRouterUrl(router: Router, defaultScheme: String, defaultHost: String): String {
        val scheme = if (router.scheme.isEmpty()) defaultScheme else router.scheme
        val host = if (router.host.isEmpty()) defaultHost else router.host
        val path = router.value
        if (scheme.contains(":") || scheme.contains("/")) {
            throw IllegalArgumentException("[CRouter] Scheme '$scheme' must not be null and must not contains ':' or '/'")
        }
        if (host.contains('/')) {
            throw IllegalArgumentException("[CRouter] Host '$host' must not be null and must not contains '/'")
        }
        if (path.isNotEmpty() && !path.startsWith('/')) {
            throw IllegalArgumentException("[CRouter] Path '$path' must be '' or start with '/'")
        }

        return "$scheme://$host$path"
    }

    fun escapeUrl(url: String): String {
        return "\"" + url.replace("\\", "\\\\") + "\""
    }
}