package me.wcy.crouter.compiler

import me.wcy.router.annotation.Router

/**
 * Created by wcy on 2019/7/19.
 */
object ProcessorUtils {
    const val PARAM_NAME = "routerSet"
    const val METHOD_NAME = "loadRouter"
    const val PACKAGE_NAME = "me.wcy.router.annotation.loader"
    const val JAVADOC = "DO NOT EDIT THIS FILE! IT WAS GENERATED BY CROUTER.\n"

    fun formatModuleName(moduleName: String): String {
        return moduleName.replace('-', '_')
    }

    fun getRouterPath(router: Router): String {
        val path = router.value
        if (path.isNotEmpty() && !path.startsWith('/')) {
            throw IllegalArgumentException("[CRouter] Path '$path' must be '' or start with '/'")
        }
        return path
    }

    fun escapePath(url: String): String {
        return "\"" + url.replace("\\", "\\\\") + "\""
    }
}