package me.wcy.router.annotation

/**
 * Created by wangchenyan.top on 2024/6/6.
 */
object CRouterConsts {
    const val JAVADOC = "Automatically generated by CRouter."

    const val FINAL_REGISTERER_CLASS_NAME = "me.wcy.router.RouteRegisterer"
    val FINAL_REGISTERER_CLASS_CONTENT =
        """
            package me.wcy.router
            
            /**
             * $JAVADOC
             */
            class RouteRegisterer : IRouteRegisterer {
                override fun registerModuleRoutes() {
                }
            }
        """.trimIndent()
    const val FINAL_REGISTERER_CLASS_METHOD_NAME = "registerModuleRoutes"

    const val MODULE_REGISTERER_PACKAGE_NAME = "me.wcy.router.generate.register"
    const val MODULE_REGISTERER_CLASS_NAME_PREFIX = "CRouteRegisterer_"
    const val MODULE_REGISTERER_CLASS_METHOD_NAME = "register"
}